import React, { useState } from "react";
import "./styles.css";

var emojiDictionary = {
  "😀": "Grinning Face",
  "😃": "Grinning Face with Big Eyes",
  "😄": "Grinning Face with Smiling Eyes",
  "😁": "Beaming Face with Smiling Eyes",
  "😆": "Grinning Squinting Face",
  "😅": "Grinning Face with Sweat",
  "🤣": "Rolling on the Floor Laughing",
  "😂": "Face with Tears of Joy",
  "🙂": "Slightly Smiling Face",
  "🙃": "Upside-Down Face",
  "😉": "Winking Face",
  "😊": "Smiling Face with Smiling Eyes",
  "😇": "Smiling Face with Halo",
  "🥰": "Smiling Face with Hearts",
  "😍": "Smiling Face with Heart-Eyes",
  "🤩": "Star-Struck",
  "😘": "Face Blowing a Kiss",
  "😗": "Kissing Face",
  "😚": "Kissing Face with Closed Eyes",
  "😙": "Kissing Face with Smiling Eyes",
  "😋": "Face Savoring Food",
  "😛": "Face with Tongue",
  "😜": "Winking Face with Tongue",
  "🤪": "Zany Face",
  "😝": "Squinting Face with Tongue",
  "🤑": "Money-Mouth Face",
  "🤗": "Hugging Face",
  "🤭": "Face with Hand Over Mouth",
  "🤫": "Shushing Face",
  "🤔": "Thinking Face",
  "🤐": "Zipper-Mouth Face",
  "🤨": "Face with Raised Eyebrow",
  "😐": "Neutral Face",
  "😑": "Expressionless Face",
  "😶": "Face Without Mouth",
  "😏": "Smirking Face",
  "😒": "Unamused Face",
  "🙄": "Face with Rolling Eyes",
  "😬": "Grimacing Face",
  "🤥": "Lying Face",
  "😌": "Relieved Face",
  "😔": "Pensive Face",
  "😪": "Sleepy Face",
  "🤤": "Drooling Face",
  "😴": "Sleeping Face",
  "😷": "Face with Medical Mask",
  "🤒": "Face with Thermometer",
  "🤕": "Face with Head-Bandage",
  "🤢": "Nauseated Face",
  "🤮": "Face Vomiting",
  "🤧": "Sneezing Face",
  "🥵": "Hot Face",
  "🥶": "Cold Face",
  "🥴": "Woozy Face",
  "😵": "Dizzy Face",
  "🤯": "Exploding Head",
  "🤠": "Cowboy Hat Face",
  "🥳": "Partying Face",
  "😎": "Smiling Face with Sunglasses",
  "🤓": "Nerd Face",
  "🧐": "Face with Monocle",
  "😕": "Confused Face",
  "😟": "Worried Face",
  "🙁": "Slightly Frowning Face",
  "☹️": "Frowning Face",
  "😮": "Face with Open Mouth",
  "😯": "Hushed Face",
  "😲": "Astonished Face",
  "😳": "Flushed Face",
  "🥺": "Pleading Face",
  "😦": "Frowning Face with Open Mouth",
  "😧": "Anguished Face",
  "😨": "Fearful Face",
  "😰": "Anxious Face with Sweat",
  "😥": "Sad but Relieved Face",
  "😢": "Crying Face",
  "😭": "Loudly Crying Face",
  "😱": "Face Screaming in Fear",
  "😖": "Confounded Face",
  "😣": "Persevering Face",
  "😞": "Disappointed Face",
  "😓": "Downcast Face with Sweat",
  "😩": "Weary Face",
  "😫": "Tired Face",
  "🥱": "Yawning Face",
  "😤": "Face with Steam From Nose",
  "😡": "Pouting Face",
  "😠": "Angry Face",
  "🤬": "Face with Symbols on Mouth",
  "😈": "Smiling Face with Horns",
  "👿": "Angry Face with Horns",
  "💀": "Skull",
  "☠️": "Skull and Crossbones",
  "💩": "Pile of Poo",
  "🤡": "Clown Face",
  "👹": "Ogre",
  "👺": "Goblin",
  "👻": "Ghost",
  "👽": "Alien",
  "👾": "Alien Monster",
  "🤖": "Robot",
  "😺": "Grinning Cat",
  "😸": "Grinning Cat with Smiling Eyes",
  "😹": "Cat with Tears of Joy",
  "😻": "Smiling Cat with Heart-Eyes",
  "😼": "Cat with Wry Smile",
  "😽": "Kissing Cat",
  "🙀": "Weary Cat",
  "😿": "Crying Cat",
  "😾": "Pouting Cat",
  "💋": "Kiss Mark",
  "👋": "Waving Hand",
  "🤚": "Raised Back of Hand",
  "🖐️": "Hand with Fingers Splayed",
  "✋": "Raised Hand",
  "🖖": "Vulcan Salute",
  "👌": "OK Hand",
  "🤏": "Pinching Hand",
  "✌️": "Victory Hand",
  "🤞": "Crossed Fingers",
  "🤟": "Love-You Gesture",
  "🤘": "Sign of the Horns",
  "🤙": "Call Me Hand",
  "👈": "Backhand Index Pointing Left",
  "👉": "Backhand Index Pointing Right",
  "👆": "Backhand Index Pointing Up",
  "🖕": "Middle Finger",
  "👇": "Backhand Index Pointing Down",
  "☝️": "Index Pointing Up",
  "👍": "Thumbs Up",
  "👎": "Thumbs Down",
  "✊": "Raised Fist",
  "👊": "Oncoming Fist",
  "🤛": "Left-Facing Fist",
  "🤜": "Right-Facing Fist",
  "👏": "Clapping Hands",
  "🙌": "Raising Hands",
  "👐": "Open Hands",
  "🤲": "Palms Up Together",
  "🤝": "Handshake",
  "🙏": "Folded Hands",
  "✍️": "Writing Hand",
  "💅": "Nail Polish",
  "🤳": "Selfie",
  "💪": "Flexed Biceps",
  "🦾": "Mechanical Arm",
  "🦿": "Mechanical Leg",
  "🦵": "Leg",
  "🦶": "Foot",
  "👂": "Ear",
  "🦻": "Ear with Hearing Aid",
  "👃": "Nose",
  "🧠": "Brain",
  "🦷": "Tooth",
  "🦴": "Bone",
  "👀": "Eyes",
  "👁️": "Eye",
  "👅": "Tongue",
  "👄": "Mouth",
  "👶": "Baby",
  "🧒": "Child",
  "👦": "Boy",
  "👧": "Girl",
  "🧑": "Person",
  "👱": "Person: Blond Hair",
  "👨": "Man",
  "🧔": "Person: Beard",
  "👨‍🦰": "Man: Red Hair",
  "👨‍🦱": "Man: Curly Hair",
  "👨‍🦳": "Man: White Hair",
  "👨‍🦲": "Man: Bald",
  "👩": "Woman",
  "👩‍🦰": "Woman: Red Hair",
  "🧑‍": "Person: Red Hair",
  "👩‍🦱": "Woman: Curly Hair",
  "👩‍🦳": "Woman: White Hair",
  "👩‍🦲": "Woman: Bald",
  "👱‍♀️": "Woman: Blond Hair",
  "👱‍♂️": "Man: Blond Hair",
  "🧓": "Older Person",
  "👴": "Old Man",
  "👵": "Old Woman",
  "🙍": "Person Frowning",
  "🙍‍♂️": "Man Frowning",
  "🙍‍♀️": "Woman Frowning",
  "🙎": "Person Pouting",
  "🙎‍♂️": "Man Pouting",
  "🙎‍♀️": "Woman Pouting",
  "🙅": "Person Gesturing No",
  "🙅‍♂️": "Man Gesturing No",
  "🙅‍♀️": "Woman Gesturing No",
  "🙆": "Person Gesturing OK",
  "🙆‍♂️": "Man Gesturing OK",
  "🙆‍♀️": "Woman Gesturing OK",
  "💁": "Person Tipping Hand",
  "💁‍♂️": "Man Tipping Hand",
  "💁‍♀️": "Woman Tipping Hand",
  "🙋": "Person Raising Hand",
  "🙋‍♂️": "Man Raising Hand",
  "🙋‍♀️": "Woman Raising Hand",
  "🧏": "Deaf Person",
  "🧏‍♂️": "Deaf Man",
  "🧏‍♀️": "Deaf Woman",
  "🙇": "Person Bowing",
  "🙇‍♂️": "Man Bowing",
  "🙇‍♀️": "Woman Bowing",
  "🤦": "Person Facepalming",
  "🤦‍♂️": "Man Facepalming",
  "🤦‍♀️": "Woman Facepalming",
  "🤷": "Person Shrugging",
  "🤷‍♂️": "Man Shrugging",
  "🤷‍♀️": "Woman Shrugging",
  "👣": "Footprints",
  "🧳": "Luggage",
  "🌂": "Closed Umbrella",
  "☂️": "Umbrella",
  "🎃": "Jack-O-Lantern",
  "🧵": "Thread",
  "🧶": "Yarn",
  "👓": "Glasses",
  "🕶️": "Sunglasses",
  "🥽": "Goggles",
  "🥼": "Lab Coat",
  "🦺": "Safety Vest",
  "👔": "Necktie",
  "👕": "T-Shirt",
  "👖": "Jeans",
  "🧣": "Scarf",
  "🧤": "Gloves",
  "🧥": "Coat",
  "🧦": "Socks",
  "👗": "Dress",
  "👘": "Kimono",
  "🥻": "Sari",
  "🩱": "One-Piece Swimsuit",
  "🩲": "Briefs",
  "🩳": "Shorts",
  "👙": "Bikini",
  "👚": "Woman’s Clothes",
  "👛": "Purse",
  "👜": "Handbag",
  "👝": "Clutch Bag",
  "🎒": "Backpack",
  "👞": "Man’s Shoe",
  "👟": "Running Shoe",
  "🥾": "Hiking Boot",
  "🥿": "Flat Shoe",
  "👠": "High-Heeled Shoe",
  "👡": "Woman’s Sandal",
  "🩰": "Ballet Shoes",
  "👢": "Woman’s Boot",
  "👑": "Crown",
  "👒": "Woman’s Hat",
  "🎩": "Top Hat",
  "🎓": "Graduation Cap",
  "🧢": "Billed Cap",
  "⛑️": "Rescue Worker’s Helmet",
  "💄": "Lipstick",
  "💍": "Ring",
  "💼": "Briefcase",
  "🩸": "Drop of Blood",
  "🙈": "See-No-Evil Monkey",
  "🙉": "Hear-No-Evil Monkey",
  "🙊": "Speak-No-Evil Monkey",
  "💥": "Collision",
  "💫": "Dizzy",
  "💦": "Sweat Droplets",
  "💨": "Dashing Away",
  "🐵": "Monkey Face",
  "🐒": "Monkey",
  "🦍": "Gorilla",
  "🦧": "Orangutan",
  "🐶": "Dog Face",
  "🐕": "Dog",
  "🦮": "Guide Dog",
  "🐕‍🦺": "Service Dog",
  "🐩": "Poodle",
  "🐺": "Wolf",
  "🦊": "Fox",
  "🦝": "Raccoon",
  "🐱": "Cat Face",
  "🐈": "Cat",
  "🦁": "Lion",
  "🐯": "Tiger Face",
  "🐅": "Tiger",
  "🐆": "Leopard",
  "🐴": "Horse Face",
  "🐎": "Horse",
  "🦄": "Unicorn",
  "🦓": "Zebra",
  "🦌": "Deer",
  "🐮": "Cow Face",
  "🐂": "Ox",
  "🐃": "Water Buffalo",
  "🐄": "Cow",
  "🐷": "Pig Face",
  "🐖": "Pig",
  "🐗": "Boar",
  "🐽": "Pig Nose",
  "🐏": "Ram",
  "🐑": "Ewe",
  "🐐": "Goat",
  "🐪": "Camel",
  "🐫": "Two-Hump Camel",
  "🦙": "Llama",
  "🦒": "Giraffe",
  "🐘": "Elephant",
  "🦏": "Rhinoceros",
  "🦛": "Hippopotamus",
  "🐭": "Mouse Face",
  "🐁": "Mouse",
  "🐀": "Rat",
  "🐹": "Hamster",
  "🐰": "Rabbit Face",
  "🐇": "Rabbit",
  "🐿️": "Chipmunk",
  "🦔": "Hedgehog",
  "🦇": "Bat",
  "🐻": "Bear",
  "🐨": "Koala",
  "🐼": "Panda",
  "🦥": "Sloth",
  "🦦": "Otter",
  "🦨": "Skunk",
  "🦘": "Kangaroo",
  "🦡": "Badger",
  "🐾": "Paw Prints",
  "🦃": "Turkey",
  "🐔": "Chicken",
  "🐓": "Rooster",
  "🐣": "Hatching Chick",
  "🦠": "Microbe",
  "💐": "Bouquet",
  "🌸": "Cherry Blossom",
  "💮": "White Flower",
  "🏵️": "Rosette",
  "🌹": "Rose",
  "🥀": "Wilted Flower",
  "🌺": "Hibiscus",
  "🌻": "Sunflower",
  "🌼": "Blossom",
  "🌷": "Tulip",
  "🌱": "Seedling",
  "🌲": "Evergreen Tree",
  "🧉": "Mate",
  "🧊": "Ice",
  "🥢": "Chopsticks",
  "🍽️": "Fork and Knife with Plate",
  "🍴": "Fork and Knife",
  "🥄": "Spoon",
  "🕴️": "Person in Suit Levitating",
  "🧗": "Person Climbing",
  "🧗‍♂️": "Man Climbing",
  "🧗‍♀️": "Woman Climbing",
  "🤺": "Person Fencing",
  "🏇": "Horse Racing",
  "⛷️": "Skier",
  "🏂": "Snowboarder",
  "🏌️": "Person Golfing",
  "🏌️‍♂️": "Man Golfing",
  "🏌️‍♀️": "Woman Golfing",
  "🏄": "Person Surfing",
  "🏄‍♂️": "Man Surfing",
  "🏄‍♀️": "Woman Surfing",
  "🚣": "Person Rowing Boat",
  "🚣‍♂️": "Man Rowing Boat",
  "🚣‍♀️": "Woman Rowing Boat",
  "🏊": "Person Swimming",
  "🏊‍♂️": "Man Swimming",
  "🏊‍♀️": "Woman Swimming",
  "⛹️": "Person Bouncing Ball",
  "⛹️‍♂️": "Man Bouncing Ball",
  "⛹️‍♀️": "Woman Bouncing Ball",
  "🏋️": "Person Lifting Weights",
  "🏋️‍♂️": "Man Lifting Weights",
  "🏋️‍♀️": "Woman Lifting Weights",
  "🚴": "Person Biking",
  "🚴‍♂️": "Man Biking",
  "🚴‍♀️": "Woman Biking",
  "🚵": "Person Mountain Biking",
  "🚵‍♂️": "Man Mountain Biking",
  "🚵‍♀️": "Woman Mountain Biking",
  "🤸": "Person Cartwheeling",
  "🤹‍♀️": "Woman Juggling",
  "🧘": "Person in Lotus Position",
  "🧘‍♂️": "Man in Lotus Position",
  "🧘‍♀️": "Woman in Lotus Position",
  "🎪": "Circus Tent",
  "🛹": "Skateboard",
  "🛶": "Canoe",
  "🎗️": "Reminder Ribbon",
  "🎟️": "Admission Tickets",
  "🎫": "Ticket",
  "🎖️": "Military Medal",
  "🏆": "Trophy",
  "🧩": "Puzzle Piece",
  "♟️": "Chess Pawn",
  "🎭": "Performing Arts",
  "🎨": "Artist Palette",
  "🗨️": "Left Speech Bubble",
  "🗯️": "Right Anger Bubble",
  "💭": "Thought Balloon",
  "💤": "Zzz",
  "♨️": "Hot Springs",
  "💈": "Barber Pole",
  "🛑": "Stop Sign",
  "": "Meaning will appear here..."
};

var emojiWeKnow = Object.keys(emojiDictionary);
var headingText = "Inside Outtt ";
var colorb = "white";

export default function App() {
  const [meaning, setMeaning] = useState("");

  function emojiInputHandler(event) {
    var userInput = event.target.value;
    var meaning = emojiDictionary[userInput];
    if (meaning === undefined) {
      meaning = "Not present in the DataBase.";
    }
    setMeaning(meaning);
  }

  function emojiClickHandler(emoji) {
    var meaning = emojiDictionary[emoji];
    setMeaning(meaning);
  }

  return (
    <div className="App">
      <header class="head">
        <h1 style={{ color: colorb }}>{headingText}</h1>
      </header>
      <input
        onChange={emojiInputHandler}
        placeholder={"Enter the emoji here...."}
      ></input>
      <div id="output">
        <b>{meaning}</b>
      </div>
      <h3>Emoji's you can Click On</h3>
      {emojiWeKnow.map(function (emoji) {
        return (
          <span
            class="idk"
            onClick={() => emojiClickHandler(emoji)}
            style={{ fontSize: "2rem", padding: "0.6rem", cursor: "pointer" }}
            key={emoji}
          >
            {emoji}
          </span>
        );
      })}

      <footer>
        <div id="foot">
          <a id="link" href="https://mahikaportfolio.netlify.app/projects.html">
            View Other Projects
          </a>
        </div>
      </footer>
    </div>
  );
}
